settings:
  title: 'Sovryn Status Page'
  url: 'https://status.sovryn.app' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: sovryn-app # unique identifier
    name: www.sovryn.app
#    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.sovryn.app/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: live-sovryn-app
    name: live.sovryn.app
    url: 'https://live.sovryn.app'
    method: GET
    expectStatus: 200

  - id: bitocracy-sovryn-app
    name: bitocracy.sovryn.app
    url: 'https://bitocracy.sovryn.app'
    method: GET
    expectStatus: 200

  - id: bridge-sovryn-app
    name: bridge.sovryn.app
    url: 'https://bridge.sovryn.app'
    method: GET
    expectStatus: 200

  - id: sovryn-app-blog
    name: The Sovryn Blog
    url: 'https://www.sovryn.app/blog'
    method: GET
    expectStatus: 200

  - id: mainnet-sovryn-app
    name: RSK Node
    url: 'https://mainnet.sovryn.app'
    method: GET
    expectStatus: 200

  - id: backend-sovryn-app
    name: API service
    url: 'https://backend.sovryn.app'
    method: GET
    expectStatus: 200
